server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
  data:
    redis:
      host: k10a306.p.ssafy.io
      port: 6379
      password: ssafy
  datasource:
    url: jdbc:postgresql://k10a306.p.ssafy.io:5432/postgres
    username: postgres
    password: ssafy
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    s3:
      bucket: dagak
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA4PE75RA3RF4YKTN4
      secret-key: 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

